inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-sorbet
  - rubocop-minitest
  - rubocop-rails
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - "sorbet/**/*"

Sorbet:
  Enabled: true

Sorbet/StrictSigil:
  Enabled: true
  Exclude:
    - "test/*"

Minitest:
  Enabled: true

Minitest/MultipleAssertions:
  Max: 6

Rails:
  Enabled: true

Rails/RefuteMethods:
  EnforcedStyle: refute

Rake:
  Enabled: true
