inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-sorbet
  - rubocop-minitest
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - "sorbet/**/*"

Naming/FileName:
  Exclude:
    - "lib/lunchmoney-ruby.rb" # Due to the gem name this file needs to be kabob case instead of snake case

Sorbet:
  Enabled: true

Sorbet/FalseSigil:
  Exclude:
    - ".toys/**/*"

Sorbet/StrictSigil:
  Enabled: true
  Exclude:
    - "test/*"
    - ".toys/**/*"

Sorbet/ForbidTStruct:
  Enabled: true
  # Context for why this is preferable https://github.com/Shopify/rubocop-sorbet/pull/178#issuecomment-1739924189

Sorbet/RedundantExtendTSig:
  Enabled: true

Minitest:
  Enabled: true

Minitest/MultipleAssertions:
  Max: 6

Rails:
  Enabled: true

Rails/RefuteMethods:
  EnforcedStyle: refute
