name: Check Pipeline

on:
  push:
    branches-ignore:
        - main
    paths-ignore:
        - ".gitignore"
        - "README.md"
    tags-ignore:
        - v*

jobs:
  update-rbis:
    name: RBI Updater
    uses: halorrr/lunchmoney/.github/workflows/dependabot-rbi-updater.yml@main
    secrets: inherit

  ci:
    needs: update-rbis
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    name: "CI"
    uses: halorrr/lunchmoney/.github/workflows/ci.yml@main
    secrets: inherit
