name: Check Pipeline

on:
  push:
    branches-ignore:
        - main
    paths-ignore:
        - ".gitignore"
        - "README.md"
    tags-ignore:
        - v*

jobs:
  update-rbis:
    name: RBI Updater
    uses: ./.github/workflows/dependabot-rbi-updater.yml
    secrets: inherit

  ci:
    needs: update-rbis
    if: always() && contains(needs.*.result, 'skipped')
    name: "CI"
    uses: ./.github/workflows/ci.yml
    secrets: inherit
