name: Publish Gem

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build & Release Gem
    runs-on: ubuntu-latest
    environment: rubygems

    permissions:
      contents: write
      id-token: write

    steps:
      # Set up
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      # Release
      - name: Publish to RubyGems
        uses: rubygems/release-gem@v1

