name: Release Pipeline

on:
    workflow_dispatch:
    push:
        tags:
            - v*

jobs:
    ci:
        name: "CI"
        uses: mmenanno/lunchmoney/.github/workflows/ci.yml@main
        secrets: inherit
    release:
        permissions:
            contents: write
            id-token: write

        needs: ci
        if: always() && !contains(needs.*.result, 'failed') && !contains(needs.*.result, 'cancelled')
        name: "Release"
        uses: mmenanno/lunchmoney/.github/workflows/publish_gem.yml@main
        secrets: inherit
